services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smartcare_db
      - POSTGRES_USER=smartcare_user
      - POSTGRES_PASSWORD=030700

  web:
    build: .
    command: gunicorn smartcare.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://smartcare_user:030700@db:5432/smartcare_db

  drf_services:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://smartcare_user:030700@db:5432/smartcare_db

volumes:
  postgres_data: