services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-smartcare_db}
      - POSTGRES_USER=${DB_USER:-smartcare_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-030700}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - backend

  web:
    build: .
    command: gunicorn smartcare.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER:-smartcare_user}:${DB_PASSWORD:-030700}@db:5432/${DB_NAME:-smartcare_db}
      - DB_NAME=${DB_NAME:-smartcare_db}
      - DB_USER=${DB_USER:-smartcare_user}
      - DB_PASSWORD=${DB_PASSWORD:-030700}
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - backend

  drf_services:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER:-smartcare_user}:${DB_PASSWORD:-030700}@db:5432/${DB_NAME:-smartcare_db}
      - DB_NAME=${DB_NAME:-smartcare_db}
      - DB_USER=${DB_USER:-smartcare_user}
      - DB_PASSWORD=${DB_PASSWORD:-030700}
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: