# Generated by Django 5.0.6 on 2024-07-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_pendingregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
