# Generated by Django 5.0.6 on 2024-07-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='patient_type',
            field=models.CharField(choices=[('nhs', 'NHS'), ('private', 'Private')], default='nhs', max_length=10),
        ),
    ]
