# Generated by Django 5.0.6 on 2024-07-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0008_user_date_of_birth_user_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, choices=[('EYE', 'Eye Specialist'), ('GYN', 'Gynecologist'), ('ORT', 'Orthopedic'), ('PED', 'Pediatrician'), ('PSY', 'Psychiatrist'), ('RAD', 'Radiologist'), ('URO', 'Urologist')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patient_type',
            field=models.CharField(choices=[('NHS', 'NHS'), ('PRIVATE', 'Private')], default='NHS', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
