# Generated by Django 5.0.6 on 2024-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_specialty_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patient_type',
            field=models.CharField(choices=[('NHS', 'NHS Patient'), ('PRIVATE', 'Private Patient')], default='NHS', max_length=7),
        ),
    ]
