# Generated by Django 5.0.6 on 2024-07-08 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='completedforwardedcanceled',
            name='date_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
