# Generated by Django 5.0.6 on 2024-07-10 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_completedforwardedcanceled_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('NHS_PATIENT', 'NHS Patient'), ('PRIVATE_PATIENT', 'Private Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse')], max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient_type', models.CharField(choices=[('ALL', 'All Patients'), ('NHS', 'NHS Patients'), ('PRIVATE', 'Private Patients')], default='ALL', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('NHS_PATIENT', 'NHS Patient'), ('PRIVATE_PATIENT', 'Private Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse')], max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_appointment_invoice',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('SURGERY', 'Surgery'), ('GENERAL_CHECKUP', 'General Checkup'), ('DENTAL', 'Dental Consultation'), ('PHYSICAL_THERAPY', 'Physical Therapy'), ('DERMATOLOGY', 'Dermatology'), ('CARDIOLOGY', 'Cardiology'), ('NEUROLOGY', 'Neurology')], default='GENERAL_CHECKUP', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default="00:00:00"),  # Corrected default value to be a string
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='fees',
            field=models.ManyToManyField(related_name='invoices', to='appointments.fee'),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionrequest',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.prescription'),
        ),
    ]
