# Generated by Django 5.0.6 on 2024-07-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_defaultrate_fee_prescriptionrequest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
