# Generated by Django 5.0.6 on 2024-07-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name_plural': 'Fees'},
        ),
    ]
