# Generated by Django 5.0.6 on 2024-07-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred_to',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referring_practitioner',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
    ]
