# Generated by Django 5.0.6 on 2024-07-11 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_specialty_alter_user_groups_and_more'),
        ('collaboration', '0002_remove_referral_patient_remove_referral_referred_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedpatientrecord',
            old_name='created_at',
            new_name='shared_date',
        ),
        migrations.RemoveField(
            model_name='sharedpatientrecord',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='sharedpatientrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sharedpatientrecord',
            name='gp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authentication.gpdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedpatientrecord',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedpatientrecord',
            name='shared_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
